version: '3.8'
services:
  app:
    build: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/taskrouter
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ./data:/app/data

  dashboard:
    build: .
    command: streamlit run src/dashboard/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - 8501:8501
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: taskrouter
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

volumes:
  postgres_data: